name: FDU Sports Auto-Reservation

on:
  workflow_dispatch:
  schedule:
    - cron: '1 16 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 我们将给这一步加上一个ID, 方便后续引用
      - name: Run the reservation script
        id: run_script # <--- 新增ID
        env:
          USER_ID: ${{ secrets.USER_ID }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PHONE: ${{ secrets.USER_PHONE }}
          YOUR_EMAIL: ${{ secrets.YOUR_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py

      # --- 这是新增的、最关键的“上传”步骤 ---
      - name: Upload failure artifacts
        # 这个条件意味着: 仅在前面的 "Run the reservation script" 步骤失败时, 才执行此操作
        if: failure() && steps.run_script.conclusion == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs # 上传的包裹名称
          path: |
            error_screenshot.png
            error_page_source.html
      # ------------------------------------
